version: "3.9"

services:
  db:
    image: postgres:15
    container_name: imdb_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imdb_etl
    depends_on:
      - db
    volumes:
      - ./data/logs:/app/data/logs
    command: [ "sh", "/app/start.sh" ]

volumes:
  pgdata:

